### ISSUE TITLE
undefined method for app_token

### ISSUE THREAD

**Issue by ryanatwork** [Chicago/windy#2]
Hi,

I'm trying to specify my app_token as shown in the readme.  Windy.app_token = "abc123"

I'm getting the following error:

ruby-1.9.2-p290 > irb
pry(main)> require 'windy'
=> true
pry(main)> Windy
=> Windy
pry(main)> Windy.app_token = "abc123"
NoMethodError: undefined method `app_token=' for Windy:Module
from (pry):3:in`<main>'

**Comment by srobbin** [comment]
Hi Ryan,

I think I see what's going on here. The code on Github has the app_token attribute (v0.1.1), but the RubyGems gem is still an older version (v0.1.0), and doesn't have that attribute. I'm working on updating the Gem, but in the meantime, if you're interested in using Windy, I suggest installing from the Github code. That said, I'll let you know when everything is sorted out.

Cheers,
Scott

**Comment by ryanatwork** [comment]
Thanks, I'll do that for now.

**Comment by ryanatwork** [comment]
Also, if you want help updating the gem let me know what needs to be done I'd be interested on working on it.

**Comment by srobbin** [comment]
Hi Ryan,

The gem is now updated. Thanks so much for letting us know about this.

Cheers,
Scott

**Comment by ryanatwork** [comment]
Awesome, thanks!
